#!/bin/bash

CSVFile=$1

export CLASSPATH=/usr/local/Cellar/saxon/10.3/libexec/saxon-he-10.3.jar

DestinationFile=$2


#
# Strip commas between quotes
#



#          remove commas in quotes    

#cat "$1" |  sed -e 's/\(\"[^",]\+\),\([^",]*\)/\1 \2/g' -e 's/\"//g'  > "$2"

cat "$1" | awk -F'"' -v OFS='' '{ for (i=2; i<=NF; i+=2) gsub(",", "", $i) } 1' > "$2"



#java net.sf.saxon.Transform -it:csvConvert csvconvert.xsl root=routes record=route csvFile="$2" -o:routeList.xml

