#!/bin/bash

CSVFile=$1

export CLASSPATH=/usr/local/Cellar/saxon/10.3/libexec/saxon-he-10.3.jar

DestinationFile=$2

XSLFile=$3

#
# Strip Quotes from file
#



#        remove web links     change route to name  change URL to date     Remove location levels  1st line spaces   remove commas in quotes        remove "     Remove empty spaces
cat "$1" | sed 's/:.*\///g' | sed 's/Route/Name/g' | sed 's/URL/Date/g' | sed 's/ >.*,https/,/g' | sed '1s/ //g' |                               tr -d '"' | sed 's/,,/,0,/g' > "$2"

java net.sf.saxon.Transform -it:csvConvert csvconvert.xsl root=routes record=route csvFile=routeFinder.txt -o:routeList.xml
java net.sf.saxon.Transform routeList.xml state1.xsl -o:state1.html

